export const FETCH_TRACKS = 'FETCH_TRACKS';
export const TRACKS_LOADING = 'TRACKS_LOADING';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';

export const ADD_RECENT = 'ADD_RECENT';
export const PERSIST_RECENT = 'PERSIST_RECENT';
export const LOAD_RECENT = 'LOAD_RECENT';

